"""
push_service.py — Web Push notification service using VAPID + ecdsa (pure Python).

Strategy: "Empty push + SW fetch"
  - Server signs VAPID JWT using `ecdsa` (pure Python, no Rust/C required)
  - Sends an empty push to the browser's push endpoint (no encrypted payload)
  - Notification worker sends an empty push to wake the Service Worker
  - Service Worker receives the push event, fetches /api/v1/push/latest-notification
    to get the actual notification content, then shows it to the user

This avoids the need for AES-128-GCM payload encryption (which requires `cryptography`
and cannot be built on 32-bit Linux servers without a Rust toolchain).

Handles:
- send_push_to_users: worker-side Web Push delivery
- enqueue_match_resolved_notifications: queue result notifications
- enqueue_post_liked_notification: queue post like notification
- enqueue_post_commented_notifications: queue post comment notifications
"""

import asyncio
import base64
import binascii
import hashlib
import json
import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence
from urllib.parse import urlparse
from uuid import UUID

import ecdsa as _ecdsa
import ecdsa.util as _ecdsa_util
import httpx
from dotenv import load_dotenv
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Bet, Notification, ProfilePostComment, ProfileStatusPost, PushSubscription, User
from app.services.notification_queue import enqueue_web_push

logger = logging.getLogger(__name__)
ENV_PATH = Path(__file__).resolve().parents[2] / ".env"


class PushConfigurationError(RuntimeError):
    """Raised when local Web Push/VAPID configuration is invalid."""

# ---------------------------------------------------------------------------
# Notification payloads are persisted so the web process and worker process
# can communicate through the database instead of in-memory state.
# ---------------------------------------------------------------------------


async def store_pending_notification(
    user_id: UUID, title: str, body: str, url: str = "/", icon: str = "/static/icons/icon-192.png",
    db: AsyncSession | None = None,
) -> None:
    """Persist a notification for the inbox and service-worker payload fetch."""
    if db is not None:
        try:
            notif = Notification(
                user_id=user_id, title=title, body=body, url=url, icon=icon
            )
            db.add(notif)
            await db.commit()
        except Exception:
            logger.exception("Failed to persist notification to DB for user %s", user_id)


# ---------------------------------------------------------------------------
# VAPID helpers (pure Python via ecdsa + stdlib)
# ---------------------------------------------------------------------------

def _b64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def _b64url_decode(s: str) -> bytes:
    pad = "=" * (4 - len(s) % 4) if len(s) % 4 else ""
    try:
        return base64.urlsafe_b64decode(s + pad)
    except (binascii.Error, ValueError) as exc:
        raise PushConfigurationError("Invalid VAPID_PRIVATE_KEY base64url encoding.") from exc


def _load_signing_key(private_key_raw: str) -> _ecdsa.SigningKey:
    """
    Load VAPID private key from:
      - base64url-encoded raw 32-byte EC scalar (generated by py-vapid / vapid-gen)
      - base64url-encoded DER EC private key structure (121 bytes, generated by web-push libraries)
      - PEM string (-----BEGIN EC PRIVATE KEY-----)
    """
    s = private_key_raw.strip()
    if s.startswith("-----"):
        return _ecdsa.SigningKey.from_pem(s, hashfunc=hashlib.sha256)
    # Raw base64url-encoded bytes
    raw = _b64url_decode(s)
    if len(raw) == 32:
        return _ecdsa.SigningKey.from_string(raw, curve=_ecdsa.NIST256p, hashfunc=hashlib.sha256)
    if len(raw) == 121:
        return _ecdsa.SigningKey.from_der(raw, hashfunc=hashlib.sha256)
    raise PushConfigurationError(
        f"Invalid VAPID_PRIVATE_KEY length after decoding: {len(raw)} bytes."
    )


def _make_vapid_headers(endpoint: str, private_key_str: str, email: str) -> dict:
    """
    Build VAPID Authorization + encoded public key headers for a push request.

    Returns a dict with:
      Authorization: vapid t=<jwt>,k=<pubkey_b64url>
      TTL: 86400
    """
    parsed = urlparse(endpoint)
    audience = f"{parsed.scheme}://{parsed.netloc}"

    sk = _load_signing_key(private_key_str)
    vk = sk.get_verifying_key()

    # Uncompressed EC public key: 0x04 || x (32 bytes) || y (32 bytes) = 65 bytes
    pub_bytes = b"\x04" + vk.to_string()
    pub_b64 = _b64url_encode(pub_bytes)

    # Build JWT header + claims
    jwt_header = _b64url_encode(json.dumps({"typ": "JWT", "alg": "ES256"}).encode())
    jwt_claims = _b64url_encode(
        json.dumps(
            {"aud": audience, "exp": int(time.time()) + 43200, "sub": email}
        ).encode()
    )
    signing_input = f"{jwt_header}.{jwt_claims}".encode()

    # Sign with ES256 (ECDSA P-256 + SHA-256), output raw r||s (64 bytes)
    sig = sk.sign(
        signing_input,
        hashfunc=hashlib.sha256,
        sigencode=_ecdsa_util.sigencode_string,
    )
    jwt_token = f"{jwt_header}.{jwt_claims}.{_b64url_encode(sig)}"

    return {
        "Authorization": f"vapid t={jwt_token},k={pub_b64}",
        "TTL": "86400",
        "Content-Length": "0",
    }


def _push_env() -> tuple[str, str]:
    """Load VAPID private key + claims email from .env (lazy, cached by dotenv)."""
    load_dotenv(ENV_PATH, override=False)
    private_key = os.getenv("VAPID_PRIVATE_KEY", "").strip()
    claims_email = os.getenv("VAPID_CLAIMS_EMAIL", "mailto:admin@example.com").strip()
    return private_key, claims_email


# ---------------------------------------------------------------------------
# Core send — empty push (no encrypted payload)
# ---------------------------------------------------------------------------

def _send_empty_push_sync(endpoint: str) -> bool:
    """
    Send an empty (no-payload) VAPID push to one subscription endpoint.
    Returns True  → push delivered or transient error (keep subscription)
    Returns False → subscription expired/gone (410/404 → delete from DB)
    """
    private_key, claims_email = _push_env()
    if not private_key:
        logger.warning("VAPID_PRIVATE_KEY not configured; skipping push.")
        return True

    try:
        headers = _make_vapid_headers(endpoint, private_key, claims_email)
        resp = httpx.post(endpoint, headers=headers, timeout=10.0)

        if resp.status_code in (404, 410):
            logger.info("Stale subscription removed: %s…", endpoint[:50])
            return False  # Caller will delete from DB

        if resp.status_code >= 400:
            logger.warning("Push endpoint returned %s for %s…", resp.status_code, endpoint[:50])

        return True

    except PushConfigurationError:
        raise
    except Exception as exc:
        logger.warning("Push send error for %s…: %s", endpoint[:50], exc)
        return True  # Transient — keep subscription


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

async def _delete_stale_subscriptions(db: AsyncSession, endpoints: list[str]) -> None:
    if not endpoints:
        return
    for ep in endpoints:
        sub = (
            await db.execute(
                select(PushSubscription).where(PushSubscription.endpoint == ep)
            )
        ).scalars().first()
        if sub:
            await db.delete(sub)
    await db.commit()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def send_push_to_users(
    db: AsyncSession,
    user_ids: Sequence[UUID],
    title: str,
    body: str,
    url: str = "/",
    icon: str = "/static/icons/icon-192.png",
) -> None:
    """
    1. Persist notification to DB inbox for each user.
    2. Store the payload in-memory so the SW can fetch it after wakeup.
    3. Send an empty push to every subscription belonging to the given user_ids.
    4. Clean up stale (410/404) subscriptions from the DB.
    """
    if not user_ids:
        return

    subscriptions = (
        await db.execute(
            select(PushSubscription).where(PushSubscription.user_id.in_(user_ids))
        )
    ).scalars().all()

    # Persist to inbox DB + in-memory pending store for each user
    for uid in user_ids:
        await store_pending_notification(uid, title=title, body=body, url=url, icon=icon, db=db)

    if not subscriptions:
        return

    stale_endpoints: list[str] = []

    async def _push(sub: PushSubscription) -> None:
        ok = await asyncio.to_thread(_send_empty_push_sync, sub.endpoint)
        if not ok:
            stale_endpoints.append(sub.endpoint)

    await asyncio.gather(*[_push(sub) for sub in subscriptions])
    await _delete_stale_subscriptions(db, stale_endpoints)


# ---------------------------------------------------------------------------
# Domain-specific notification enqueue helpers
# ---------------------------------------------------------------------------

async def enqueue_match_resolved_notifications(
    db: AsyncSession,
    match,
    bets: list,
    users_by_id: dict,
) -> None:
    """Queue personalised match result notifications for each bettor."""
    try:
        match_label = f"{match.home_team} vs {match.away_team}"
        score_label = f"{match.home_score} - {match.away_score}"

        for bet in bets:
            user = users_by_id.get(bet.user_id)
            if not user:
                continue

            points_earned = bet.points_earned
            if points_earned is None:
                result_msg = f"Hoàn {bet.stake:,} điểm (kèo hòa)"
                emoji = "🔄"
            elif points_earned > bet.stake:
                result_msg = f"Thắng +{points_earned - bet.stake:,} điểm 🎉"
                emoji = "🏆"
            elif points_earned == bet.stake:
                result_msg = f"Hoàn {bet.stake:,} điểm (hòa vốn)"
                emoji = "🤝"
            else:
                result_msg = f"Thua {bet.stake:,} điểm"
                emoji = "😢"

            await enqueue_web_push(
                db,
                user_id=user.id,
                title=f"{emoji} Kết quả: {match_label}",
                body=f"{score_label} — {result_msg}",
                url=f"/?match={match.id}",
                commit=False,
            )
        await db.commit()
        # TEMP_NOTIFICATION_JOB_LOG: remove after enqueue timing is verified.
        logger.info(
            "Committed match-resolved notification jobs at %s match_id=%s recipients=%s",
            datetime.now(timezone.utc).isoformat(),
            match.id,
            len(bets),
        )
    except Exception:
        logger.exception("Failed to enqueue match-resolved push notifications.")


async def enqueue_post_liked_notification(
    db: AsyncSession,
    post: ProfileStatusPost,
    actor: User,
) -> None:
    """Queue a push to the post owner when someone likes their post."""
    try:
        if post.user_id == actor.id:
            return
        actor_name = actor.display_name or actor.email.split("@")[0]
        await enqueue_web_push(
            db,
            user_id=post.user_id,
            title="❤️ Có người thích bài của bạn",
            body=f"{actor_name} đã thích bài viết của bạn",
            url=f"/community?post={post.id}",
        )
    except Exception:
        logger.exception("Failed to enqueue post-liked push notification.")


async def enqueue_post_commented_notifications(
    db: AsyncSession,
    post: ProfileStatusPost,
    actor: User,
) -> None:
    """Queue pushes to the post owner and prior commenters."""
    try:
        prior_commenter_ids_result = await db.execute(
            select(ProfilePostComment.user_id)
            .where(ProfilePostComment.post_id == post.id)
            .distinct()
        )
        prior_commenter_ids = {row[0] for row in prior_commenter_ids_result.fetchall()}

        recipient_ids = {post.user_id} | prior_commenter_ids
        recipient_ids.discard(actor.id)

        if not recipient_ids:
            return

        actor_name = actor.display_name or actor.email.split("@")[0]
        post_url = f"/community?post={post.id}"

        for uid in recipient_ids:
            if uid == post.user_id:
                title = "💬 Bình luận mới trên bài của bạn"
                body = f"{actor_name} đã bình luận vào bài của bạn"
            else:
                title = "💬 Bình luận mới"
                body = f"{actor_name} cũng bình luận vào bài này"
            await enqueue_web_push(
                db,
                user_id=uid,
                title=title,
                body=body,
                url=post_url,
                commit=False,
            )
        await db.commit()
        # TEMP_NOTIFICATION_JOB_LOG: remove after enqueue timing is verified.
        logger.info(
            "Committed post-comment notification jobs at %s post_id=%s recipients=%s",
            datetime.now(timezone.utc).isoformat(),
            post.id,
            len(recipient_ids),
        )
    except Exception:
        logger.exception("Failed to enqueue post-commented push notifications.")
